### ISSUE TITLE
[Bug]: [freeipa] AssertionError: Another instance named 'ORG-MYCOMPANY-ORG' may already exist - on pod startup

### ISSUE THREAD

**Issue by MurzNN** [Improwised/charts#54]
### Expected Behavior?

I deployed the freeipa Helm chart using my custom domain in values.yaml like this:
```yaml
hostname: freeipa.mycompany.org

args:
  realm: ORG.MYCOMPANY.ORG
  domain: org.mycompany.org
  dspassword: XXXX
  adminpassword: XXXX

ingress:
  enabled: true
  hostname: freeipa.mycompany.org
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
```

All was deployed successfully.

### Current Behavior

But I have an error on the freeipa pod startup:
```
  [error] AssertionError: Another instance named 'ORG-MYCOMPANY-ORG' may already exist
```
I tried to change the name to ORG2.MYCOMPANY.ORG and to other values, but the error still remains.

How can I fix it?

### Additional information

Full pod logs:
```
Validate installation settings ...
Another instance named 'ORG-MYCOMPANY-ORG' may already exist
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
IPA Server.
Version 4.10.1

This includes:
  * Configure a stand-alone CA (dogtag) for certificate management
  * Create and configure an instance of Directory Server
  * Create and configure a Kerberos Key Distribution Center (KDC)
  * Configure Apache (httpd)
  * Configure SID generation
  * Configure the KDC to enable PKINIT

Excluded by options:
  * Configure the NTP client (chronyd)

Warning: skipping DNS resolution of host freeipa.mycompany.org
Trust is configured but no NetBIOS domain name found, setting it now.

The IPA Master Server will be configured with:
Hostname:       freeipa.mycompany.org
IP address(es): 10.233.106.101
Domain name:    org.mycompany.org
Realm name:     ORG.MYCOMPANY.ORG

The CA will be configured with:
Subject DN:   CN=Certificate Authority,O=ORG.MYCOMPANY.ORG
Subject base: O=ORG.MYCOMPANY.ORG
Chaining:     self-signed

Disabled p11-kit-proxy
Configuring directory server (dirsrv). Estimated time: 30 seconds
  [1/42]: creating directory server instance
  [error] AssertionError: Another instance named 'ORG-MYCOMPANY-ORG' may already exist
```
